package com.student.gymdb.ui;

import com.student.gymdb.dao.MemberDAO;
import com.student.gymdb.dao.WorkoutLogDAO;
import com.student.gymdb.model.Member;
import com.student.gymdb.model.WorkoutLog;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class MainDashboard extends javax.swing.JFrame {
    private final DefaultListModel listModel = new DefaultListModel<>();

    /**
     * Creates new form MainDashboard
     */
    public MainDashboard() {
        initComponents();
        listResults.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblLogUpdate = new javax.swing.JLabel();
        tfLogID = new javax.swing.JTextField();
        lblDuration = new javax.swing.JLabel();
        tfDuration = new javax.swing.JTextField();
        btnUpdateLog = new javax.swing.JButton();
        lblMemIDUpdate = new javax.swing.JLabel();
        tfMemberIDtoChange = new javax.swing.JTextField();
        lblNewMembership = new javax.swing.JLabel();
        cbMembership = new javax.swing.JComboBox<>();
        btnUpdateMembership = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listResults = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        btnExpiringMembers = new javax.swing.JButton();
        btnHighCalorie = new javax.swing.JButton();
        lblMemberSelect = new javax.swing.JLabel();
        tfMemberIDSearch = new javax.swing.JTextField();
        btnWorkoutsByMember = new javax.swing.JButton();
        lblTrainerSelect = new javax.swing.JLabel();
        cbTrainers = new javax.swing.JComboBox<>();
        btnFindMembers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Update Records"));

        lblLogUpdate.setText("Workout Log to update:");

        lblDuration.setText("Duration (mins): ");

        btnUpdateLog.setText("Update log");
        btnUpdateLog.addActionListener(this::btnUpdateLogActionPerformed);

        lblMemIDUpdate.setText("Member ID to update: ");

        lblNewMembership.setText("New membership type:");

        cbMembership.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basic", "Premium", "Annual" }));

        btnUpdateMembership.setText("Update membership");
        btnUpdateMembership.addActionListener(this::btnUpdateMembershipActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogUpdate)
                    .addComponent(lblDuration)
                    .addComponent(lblMemIDUpdate)
                    .addComponent(lblNewMembership))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfMemberIDtoChange)
                    .addComponent(cbMembership, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfDuration)
                    .addComponent(tfLogID))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdateMembership, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLogUpdate)
                            .addComponent(tfLogID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDuration)
                            .addComponent(tfDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnUpdateLog)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMemIDUpdate)
                            .addComponent(tfMemberIDtoChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNewMembership)
                            .addComponent(cbMembership, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnUpdateMembership)))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Results"));

        jScrollPane1.setViewportView(listResults);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Search & Filters"));

        btnExpiringMembers.setText("Members expiring soon");
        btnExpiringMembers.addActionListener(this::btnExpiringMembersActionPerformed);

        btnHighCalorie.setText("Show High Calorie Workouts (>500)");
        btnHighCalorie.addActionListener(this::btnHighCalorieActionPerformed);

        lblMemberSelect.setText("Member ID:");

        btnWorkoutsByMember.setText("Show workouts");
        btnWorkoutsByMember.addActionListener(this::btnWorkoutsByMemberActionPerformed);

        lblTrainerSelect.setText("Trainer name:");

        cbTrainers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arnold", "Phil Heath", "John", "Sarah", "Mike", "Self" }));

        btnFindMembers.setText("Show members");
        btnFindMembers.addActionListener(this::btnFindMembersActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnExpiringMembers)
                        .addGap(18, 18, 18)
                        .addComponent(btnHighCalorie))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTrainerSelect)
                            .addComponent(lblMemberSelect))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfMemberIDSearch)
                            .addComponent(cbTrainers, 0, 159, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFindMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnWorkoutsByMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExpiringMembers)
                    .addComponent(btnHighCalorie))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMemberSelect)
                    .addComponent(tfMemberIDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWorkoutsByMember))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrainerSelect)
                    .addComponent(cbTrainers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindMembers))
                .addGap(0, 137, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateLogActionPerformed
        String input1 = tfLogID.getText();
        String input2 = tfDuration.getText();
        
        if (input1.isEmpty() || input2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Log ID and a new duration.", "Missing input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            int logID = Integer.parseInt(input1);
            int newDuration = Integer.parseInt(input2);
            
            WorkoutLogDAO logDAO = new WorkoutLogDAO();
            logDAO.updateWorkoutDuration(logID, newDuration);
            
            JOptionPane.showMessageDialog(this, "Successfully updated Log ID " + logID + " to new duration of " + newDuration + " minutes.", "Update successful", JOptionPane.INFORMATION_MESSAGE);
            
            tfLogID.setText("");
            tfDuration.setText("");
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Log ID and Duration MUST be valid numbers!", "Invalid input", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateLogActionPerformed

    private void btnUpdateMembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMembershipActionPerformed
        String input = tfMemberIDtoChange.getText();
        
        if (input.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Member ID to update their membership.", "Missing input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            int memberID = Integer.parseInt(input);
            String newMembership = cbMembership.getSelectedItem().toString();
            
            MemberDAO mDAO = new MemberDAO();
            mDAO.updateMembershipType(memberID, newMembership);
            
            JOptionPane.showMessageDialog(this, "Successfully updated Member ID " + memberID + " to " + newMembership + " status.", "Update Successful", JOptionPane.INFORMATION_MESSAGE);
            
            tfMemberIDtoChange.setText("");
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Member ID MUST be a number!", "Invalid input", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateMembershipActionPerformed

    private void btnExpiringMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpiringMembersActionPerformed
        MemberDAO mDAO = new MemberDAO();
        List<Member> expiring = mDAO.getPremiumMembersExpiring();
        listModel.clear();
        
        if (expiring.isEmpty()) {
            listModel.addElement("No members expiring within 30 days.");
        }
        else {
            for (Member m : expiring) {
                listModel.addElement(m);
            }
        }
    }//GEN-LAST:event_btnExpiringMembersActionPerformed

    private void btnHighCalorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHighCalorieActionPerformed
        WorkoutLogDAO logDAO = new WorkoutLogDAO();
        List<WorkoutLog> workouts = logDAO.getHighCalorieWorkouts();
        listModel.clear();
        
        if (workouts.isEmpty()) {
            listModel.addElement("No High calorie workouts in log.");
        }
        else {
            for (WorkoutLog w : workouts) {
                listModel.addElement(w);
            }
        }
    }//GEN-LAST:event_btnHighCalorieActionPerformed

    private void btnWorkoutsByMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkoutsByMemberActionPerformed
        String input = tfMemberIDSearch.getText();
        
        if (input.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Member ID.", "Missing input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            int memberID = Integer.parseInt(input);
            WorkoutLogDAO logDAO = new WorkoutLogDAO();
            List<WorkoutLog> results = logDAO.getLogbyMemberID(memberID);
            listModel.clear();
            
            if (results.isEmpty()){
                listModel.addElement("No workouts for Member ID" + memberID);
            }
            else {
                for (WorkoutLog w : results) {
                    listModel.addElement(w);
                }
            }
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Member ID MUST be a number!", "Invalid Format", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnWorkoutsByMemberActionPerformed

    private void btnFindMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindMembersActionPerformed
        String trainer = cbTrainers.getSelectedItem().toString();
        MemberDAO mDAO = new MemberDAO();
        List<Member> results = mDAO.getMembersByTrainer(trainer);
        listModel.clear();
        
        if (results.isEmpty()){
            listModel.addElement("No members assigned to trainer " + trainer);
        }
        else {
            for (Member m : results) {
                listModel.addElement(m);
            }
        }
    }//GEN-LAST:event_btnFindMembersActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExpiringMembers;
    private javax.swing.JButton btnFindMembers;
    private javax.swing.JButton btnHighCalorie;
    private javax.swing.JButton btnUpdateLog;
    private javax.swing.JButton btnUpdateMembership;
    private javax.swing.JButton btnWorkoutsByMember;
    private javax.swing.JComboBox<String> cbMembership;
    private javax.swing.JComboBox<String> cbTrainers;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblLogUpdate;
    private javax.swing.JLabel lblMemIDUpdate;
    private javax.swing.JLabel lblMemberSelect;
    private javax.swing.JLabel lblNewMembership;
    private javax.swing.JLabel lblTrainerSelect;
    private javax.swing.JList<String> listResults;
    private javax.swing.JTextField tfDuration;
    private javax.swing.JTextField tfLogID;
    private javax.swing.JTextField tfMemberIDSearch;
    private javax.swing.JTextField tfMemberIDtoChange;
    // End of variables declaration//GEN-END:variables
}
